### ISSUE TITLE
Could I release the generator model reproduced from your onnx file?

### ISSUE THREAD

**Issue by ttjjmm** [TachibanaYoshino/AnimeGANv3#11]
I reproduced the network arch of animeganv3's generator, could I release it in my repo?
by the way, I notice that you modified the AdaIN with self-adaptive affine transform directly from 3x3_conv output features to stabilize the cartoon-style formation?

**Comment by TachibanaYoshino** [comment]
Great, you made a nice discovery. By the way, you can't release the generator network just yet, you'll find out more when I release the paper. Please stay tuned.

**Comment by ttjjmm** [comment]
OK, I am eagerly looking forward to your newly-minted paper !!!
