### ISSUE TITLE
onnxruntime failed to load library 

### ISSUE THREAD

**Issue by jianchong-chen** [TachibanaYoshino/AnimeGANv3#13]
Thanks for your great work!
There is onnxruntime error when I running the exe. Even though I can process the images, but the results seem to be not as good as hope.
Then I run "pip install onnxruntime" in the cmd window with conda base virtual environment. 
But the error still exists. It's as the following:

_2022-05-18 16:19:56.9664601 [E:onnxruntime:Default, provider_bridge_ort.cc:901 onnxruntime::ProviderSharedLibrary::Ensure] Failed to load library, error code: 126
2022-05-18 16:19:56.9666273 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1624 onnxruntime::python::pybind11_init_onnxruntime_pybind11_state] Init provider bridge failed._

**Comment by Sharriyy** [comment]
> Thanks for your great work! There is onnxruntime error when I running the exe. Even though I can process the images, but the results seem to be not as good as hope. Then I run "pip install onnxruntime" in the cmd window with conda base virtual environment. But the error still exists. It's as the following:
> 
> _2022-05-18 16:19:56.9664601 [E:onnxruntime:Default, provider_bridge_ort.cc:901 onnxruntime::ProviderSharedLibrary::Ensure] Failed to load library, error code: 126 2022-05-18 16:19:56.9666273 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1624 onnxruntime::python::pybind11_init_onnxruntime_pybind11_state] Init provider bridge failed._
How much time did it take to process image?

**Comment by TachibanaYoshino** [comment]
This repository is only used as a sample program, you can try this demo on a Windows 10 machine with better cpu performance. You can ignore error notifications about onnxruntime for the time being.
