### ISSUE TITLE
arcane style model

### ISSUE THREAD

**Issue by flynnamy** [TachibanaYoshino/AnimeGANv3#17]
Hi, could you please share the exe file and model of arcane style? Thanks! @TachibanaYoshino

**Comment by TachibanaYoshino** [comment]
I am sharing the colab of the Face to Arcane style model in my [patreon](https://www.patreon.com/Asher_Chan).

**Comment by spinoza1791** [comment]
Is there a way we could also pay for a PyTorch mobile quant version (.ptl)
of the Arcane model? Something that could run on android.

**Comment by TachibanaYoshino** [comment]
@spinoza1791     For the Face to Arcane style model of AnimeGANv3, I currently export the onnx and pb forms based on the trained model.  

One more thing, I am now trying a new face to cartoon conversion by using AnimeGANv3, the expected effect can refer to the following example, the future results will be published on my [patreon](https://www.patreon.com/Asher_Chan).

![demo](https://user-images.githubusercontent.com/36946777/184468219-f8dc7f6c-312c-4215-8cd1-1498ff49bccd.png)
