### ISSUE TITLE
The online experience of AnimeGANv3 webpage is under consideration, but ...

### ISSUE THREAD

**Issue by TachibanaYoshino** [TachibanaYoshino/AnimeGANv3#19]
The online experience of AnimeGANv3 webpage is under consideration, but I have no idea about webpage deployment, hoping for good advice to help me achieve it quickly. Thx.

**Comment by TachibanaYoshino** [comment]
Because the paper has not been accepted, I have not been able to release the source code and model. This has been going on for many months. I also regret that, now.  :sweat:

**Comment by Sun-ZhenXing** [comment]
I decrypted the model file and code from huggingface, then I wrote this as a service program using `sanic`. I will not give away the content and hope you will release the paper and source code soon.

I will send you the source code.

![image](https://user-images.githubusercontent.com/44517244/194529791-3521017c-0c39-4209-9d1b-686e1fa49b15.png)

**Comment by TachibanaYoshino** [comment]
> 

I have replied to your email. The paper and source code will probably be released next year, because this year's submissions were not accepted.
I have developed online examples at huggingface. If it's a commercial deployment, cloud servers and using a domain name cost money, but I don't have the funds to do it.
