### ISSUE TITLE
ONNX model files

### ISSUE THREAD

**Issue by haile-vnu** [TachibanaYoshino/AnimeGANv3#2]
Hi @TachibanaYoshino,

Thank you for your work.
For AnimeGANv3 demo. I do not have Windows computer to run the test. Could you share your Onnx model files. So I can test them.
My email is hailh.vnu@gmail.com

Thank you @TachibanaYoshino!

**Comment by jeffhecker** [comment]
The onnx model files were posted in this repo. Although it's password protected in a zip archive I am sure you can extract the password without much effort. I wont being sharing it here but since it is quite obvious that the whole `.exe` was packed with PyInstaller you can extract the compiled `.pyc` and found the hardcoded password in two modules ending with `test_by_onnxZIP`:
<img width="643" alt="Screen Shot 2022-01-28 at 6 29 11 PM" src="https://user-images.githubusercontent.com/98587421/151531330-65494ad8-a2eb-441f-b437-a2c127e0e918.png">

**Comment by FrankyCao** [comment]
> The onnx model files were posted in this repo. Although it's password protected in a zip archive I am sure you can extract the password without much effort. I wont be sharing it here but since it is quite obvious that the whole `.exe` was packed with PyInstaller you can extract the compiled `.pyc` and found the hardcoded password in two modules ending with `test_by_onnxZIP`: <img alt="Screen Shot 2022-01-28 at 6 29 11 PM" width="643" src="https://user-images.githubusercontent.com/98587421/151531330-65494ad8-a2eb-441f-b437-a2c127e0e918.png">

thx,I found the pwd too

**Comment by Baiyuetribe** [comment]
里面的onnx文件拿到了，有人会转ncnn吗？

**Comment by spinoza1791** [comment]
Perhaps the exe has changed, but I cannot find the .pyc file you mention in the unpacked .exe? Is this solution still current? Thank you for your help.

**Comment by kaneyxx** [comment]
> Perhaps the exe has changed, but I cannot find the .pyc file you mention in the unpacked .exe? Is this solution still current? Thank you for your help.

I have the same issue here. If you found anything helpful, please let me know. Very appreciated!

**Comment by kaneyxx** [comment]
> 里面的onnx文件拿到了，有人会转ncnn吗？

大佬可以寄密码给我么？decompile一直遇到问题
kaneyxx@gmail.com
非常感谢!

**Comment by ioskevinshah** [comment]
Hello @TachibanaYoshino , @jeffhecker 

Can please share the password?

Email: ioskevinshah@gmail.com

**Comment by lllliang** [comment]
I found a .pyc file in hugging face, but this way does not work. 
Can please share the pwd ? 
Email: q1589076631@163.com
Thanks!

**Comment by TachibanaYoshino** [comment]
The current public model is not the final version, because it is prone to generate a lot of line cracks on some low-quality images. When the time comes, we will give the final onnx model.

**Comment by 2655251820** [comment]
I found a .pyc file in hugging face, but this way does not work.
Can please share the pwd ?
Email: 2655251820@qq.com
Thanks!

**Comment by TachibanaYoshino** [comment]
I share the [colab code](https://www.patreon.com/posts/colab-of-with-72136496?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=postshare_creator) based on the onnx model (unencrypted) on patreon, welcome to subscribe to my channel and get various models in advance.

**Comment by SunYu2022** [comment]
Hello @TachibanaYoshino 
Can please share the password?

yuhoisun@gmail.com

Thanks,
sun yu!

**Comment by TachibanaYoshino** [comment]
> Hello @TachibanaYoshino Can please share the password?
> 
> [yuhoisun@gmail.com](mailto:yuhoisun@gmail.com)
> 
> Thanks, sun yu!

**The model in AnimeGANv3.exe belongs to the **original old model****. Due to its sensitivity to noise, the anime images generated by the model usually have many line cracks.
When the paper is accepted by the conference, I will release the source code  of the network structure and the latest model.
You can also follow my patreon channel to get resources in advance.

**Comment by yingchengpa** [comment]
[pyinsuncomple.exe](https://download.csdn.net/download/corrupt/87514267)
cmd: pyinsuncomple.exe AnimeGANv3.exe
then , found the AnimeGANv3.exe_extracted/PYZ-00.pyz_extracted/pb_and_ONNX_model/test_by_onnxZIP.pyc.py

**Comment by buaaxiejun** [comment]
> When the paper is accepted by the conference, I will release the source code of the network structure and the latest model.
> You can also follow my patreon channel to get resources in advance.



> 里面的onnx文件拿到了，有人会转ncnn吗？

大佬，可以分享一下onnx吗？
952030879@qq.com

**Comment by buaaxiejun** [comment]
> > 里面的onnx文件拿到了，有人会转ncnn吗？
> 
> 大佬可以寄密码给我么？decompile一直遇到问题 [kaneyxx@gmail.com](mailto:kaneyxx@gmail.com) 非常感谢!

大佬，可以分享一下onnx吗？
952030879@qq.com

**Comment by liuxz656** [comment]
> [pyinsuncomple.exe](https://download.csdn.net/download/corrupt/87514267) cmd: pyinsuncomple.exe AnimeGANv3.exe then , found the AnimeGANv3.exe_extracted/PYZ-00.pyz_extracted/pb_and_ONNX_model/test_by_onnxZIP.pyc.py

Can please share the password?
thanks
505008972@qq.com

**Comment by liuxz656** [comment]
> > The onnx model files were posted in this repo. Although it's password protected in a zip archive I am sure you can extract the password without much effort. I wont be sharing it here but since it is quite obvious that the whole `.exe` was packed with PyInstaller you can extract the compiled `.pyc` and found the hardcoded password in two modules ending with `test_by_onnxZIP`: <img alt="Screen Shot 2022-01-28 at 6 29 11 PM" width="643" src="https://user-images.githubusercontent.com/98587421/151531330-65494ad8-a2eb-441f-b437-a2c127e0e918.png">
> 
> thx,I found the pwd too

Can please share the password?
thanks
[505008972@qq.com](mailto:505008972@qq.com)

**Comment by liuxz656** [comment]
> 里面的onnx文件拿到了，有人会转ncnn吗？

Can please share the password?
thanks
505008972@qq.com

**Comment by rickyjoo73** [comment]
Hi good day @TachibanaYoshino
Can please share the pwd ?
Thanks!
rickyjoo777@gmail.com

**Comment by yingchengpa** [comment]
'djfdawieurFKJAKSJFKK12338913*^&amp;^&amp;*SJFAKJFMSAKFLLKJKLJASFKJ34892'



发自我的iPhone


------------------ Original ------------------
From: rickyjoo73 ***@***.***&gt;
Date: Wed,Jun 7,2023 0:55 PM
To: TachibanaYoshino/AnimeGANv3 ***@***.***&gt;
Cc: yingcheng ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [TachibanaYoshino/AnimeGANv3] ONNX model files (Issue #2)





 
Hi good day @TachibanaYoshino
 Can please share the pwd ?
 Thanks!
 ***@***.***

**Comment by 1615070057** [comment]
> 我在patreon上分享了基于onnx模型（未加密）的[colab代码，欢迎订阅我的频道，提前获取各种模型。](https://www.patreon.com/posts/colab-of-with-72136496?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=postshare_creator) ![8%HFMQYOL(_35HPPCTXUA80](https://user-images.githubusercontent.com/36946777/190893615-f58049d4-03e7-4e60-a8fe-2b16325e5568.png)
 
订阅了你的会员, 但是并没有看到animegan v3的模型, 不带这么坑爹的吧

**Comment by rickyjoo73** [comment]
Thank you for reply to mail
and i got this code from you
djfdawieurFKJAKSJFKK12338913*^&amp;^&amp;*SJFAKJFMSAKFLLKJKLJASFKJ34892
but not working those zip file
animeganv3_H64_model0.onnx.zip, animeganv3_H40_model.onnx.zip

Please give me the right code for that zip file?

____________________________________________________________


<https://sign.mail.worksmobile.com/signature/logo/kr1/nmYmaxUwKAgmaxUwBqt-aAt./SdbwKAgmKAumaxvrFAtmKAJjFxbwKoU-KxvZaAuwFqUw>

             *                        주두철 * 대표이사


                                MOBILE   010-6588-3327
                                E-MAIL    ***@***.***
                                *ADDRESS* 서울특별시 금천구 가산디지털1로 168
                                              우림라이온스밸리 C동 1209호
____________________________________________________________


2023년 6월 9일 (금) 오후 2:54, yingcheng ***@***.***>님이 작성:

**Comment by MISThelio** [comment]
> 如果有需要，可以通过邮件联系。 ![8%HFMQYOL(_35HPPCTXUA80](https://user-images.githubusercontent.com/36946777/190893615-f58049d4-03e7-4e60-a8fe-2b16325e5568.png)

谢谢你，因此搞懂反编译基础逻辑。

**Comment by lzwRover321** [comment]
> The onnx model files were posted in this repo. Although it's password protected in a zip archive I am sure you can extract the password without much effort. I wont be sharing it here but since it is quite obvious that the whole `.exe` was packed with PyInstaller you can extract the compiled `.pyc` and found the hardcoded password in two modules ending with `test_by_onnxZIP`: <img alt="Screen Shot 2022-01-28 at 6 29 11 PM" width="643" src="https://user-images.githubusercontent.com/98587421/151531330-65494ad8-a2eb-441f-b437-a2c127e0e918.png">

thx,I found the pwd too

**Comment by hello188988** [comment]
Hi good day @TachibanaYoshino
Can please share the pwd ?
Thanks!
[hello188988@126.com](mailto:hello188988@126.com)

**Comment by dlsofree** [comment]
Where can I buy Disney models?

**Comment by pissaypratheesh** [comment]
can you please give me link to download the model and the password?
my mail id: pissaypratheesh@gmail.com

**Comment by TachibanaYoshino** [comment]
Model files can be obtained in the release section.

**Comment by JunYu1996** [comment]
can you please give me link to download the model and the password? @TachibanaYoshino
my mail id: [1430040260@qq.com]

**Comment by JunYu1996** [comment]
I found a problem, the audio of the original video will be processed when processing the video, resulting in no sound, how to solve it?  my mail 1430040260@qq.com

**Comment by JunYu1996** [comment]
I found a problem, the audio of the original video will be processed when processing the video, resulting in no sound, how to solve it? my mail [1430040260@qq.com] @TachibanaYoshino

**Comment by koala99** [comment]
> 里面的onnx文件拿到了，有人会转ncnn吗？
能分享下吗？ 或者密码： 460489105@qq.com
