### ISSUE TITLE
Dataset Release

### ISSUE THREAD

**Issue by Atharva-Phatak** [TachibanaYoshino/AnimeGANv3#20]
Thanks for the work. Will you releasing the dataset used to train the models ?

**Comment by TachibanaYoshino** [comment]
I think I'll release the dataset, but this will be decided at least after the paper is accepted by the conference.
The paper describes the concrete implementation and experimental data of my algorithm. It's really a good article.

**Comment by Atharva-Phatak** [comment]
also can you tell how did you generate the crops from movies ?? is there a script to generate hug res crops ?

**Comment by TachibanaYoshino** [comment]
The pictures are manually selected by myself, some face data still need to be adjusted with Photoshop, and finally the denoising algorithm is used to improve the image quality.
Regarding the generated sample video, I used Premiere to do video clips and add background music.

**Comment by keshav1990** [comment]
Can you please release code for Linux machine and for Disney code set too, please
