### ISSUE TITLE
sample Colab file for Video to Anime using AnimeGANv3

### ISSUE THREAD

**Issue by nichoqu** [TachibanaYoshino/AnimeGANv3#22]
Hi
I cannot find Colab for Video to Anime using AnimeGANv3. 
Is An inference notebook (Colab) for Video to Anime using AnimeGANv3?

**Comment by ElenaErikh** [comment]
I have same question. I need to convert a Video to Anime, but can`t do it. AnimeGANv3 works perfectly with images, but I couldn`t find the way to convert a video. AnimeGAN and AnimeGANv2 don`t launch due to Errors. 
Is there any way to convert it?

**Comment by TachibanaYoshino** [comment]
The code is not yet open source.
