### ISSUE TITLE
How to run code with onnxruntime-gpu？

### ISSUE THREAD

**Issue by xiaomengxiaomeng** [TachibanaYoshino/AnimeGANv3#25]
Hi @TachibanaYoshino,

Thank you for your work.
For AnimeGANv3 demo.I want to use onnxruntime-gpu to run the code, how to modify the configuration?
My email is 1197311349@qq.com

Thank you @TachibanaYoshino!

**Comment by TachibanaYoshino** [comment]
The inference setting of gui is cpu, and does not support gpu inference.
