### ISSUE TITLE
GPU与onnxruntime报错问题

### ISSUE THREAD

**Issue by liujianzuo** [TachibanaYoshino/AnimeGANv3#28]
### 有2个问题请帮忙解惑
-  不能够使用GPU。处理时候用的是cpu，这个怎么解决。
-  这个报错怎么处理。。。
  `2023-04-03 11:29:55.0674790 [E:onnxruntime:Default, provider_bridge_ort.cc:901 onnxruntime::ProviderSharedLibrary::Ensure] Failed to load library, error code: 126
2023-04-03 11:29:55.0675858 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1624 onnxruntime::python::pybind11_init_onnxruntime_pybind11_state] Init provider bridge failed.
Making: videoplayback_AnimeGANv3.mp4: 100%|███| 158/158 [03:00<00:00,  1.14s/it]
Total time : 181.23930430412292 s`

**Comment by liujianzuo** [comment]
## 补充
PS C:\Users\liujianzuo> nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Feb__8_05:53:42_Coordinated_Universal_Time_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0
PS C:\Users\liujianzuo> nvidia-smi.exe
Mon Apr  3 12:31:03 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.29                 Driver Version: 531.29       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3080 Ti    WDDM | 00000000:01:00.0 Off |                  N/A |
|  0%   33C    P8               20W / 350W|   7636MiB / 12288MiB |      4%      Default |
|                                         |                      |                  N/A |

**Comment by liuxz656** [comment]
> ## 哥，真神人也，小弟拜服！！
> ### 有2个问题请帮忙解惑
> * 不能够使用GPU。处理时候用的是cpu，这个怎么解决。
> * 这个报错怎么处理。。。
>   `2023-04-03 11:29:55.0674790 [E:onnxruntime:Default, provider_bridge_ort.cc:901 onnxruntime::ProviderSharedLibrary::Ensure] Failed to load library, error code: 126 2023-04-03 11:29:55.0675858 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1624 onnxruntime::python::pybind11_init_onnxruntime_pybind11_state] Init provider bridge failed. Making: videoplayback_AnimeGANv3.mp4: 100%|███| 158/158 [03:00<00:00,  1.14s/it] Total time : 181.23930430412292 s`

Do you have the. onnx file in the project? Isn't the author not sharing it?

**Comment by TachibanaYoshino** [comment]
The gui's exe tool only supports CPU's onnx inference. You can now use scripts to infer onnx models via GPU.
