### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by zFuRBlooDz** [TachibanaYoshino/AnimeGANv3#4]
When I try to make photo2anime I am getting this error. How can I solve this?

**Comment by jiangxinufo** [comment]
so do I

**Comment by Youngon** [comment]
> ime I am getting this error. How can I solve this?

have you solved the error yet?

**Comment by zFuRBlooDz** [comment]
> > ime I am getting this error. How can I solve this?
> 
> have you solved the error yet?

Hi, sorry for late reply. I solved this problem by choosing file directory without special characters. For example don't use characters like "ç, ö, æ...". I created "animegan-test-folder" folder in C and I am using "C:\animegan-test-folder" path. This solves my issue.
