### ISSUE TITLE
how can  i convert more than 49 images in single time in animeGan v3 exe 

### ISSUE THREAD

**Issue by aamir8825** [TachibanaYoshino/AnimeGANv3#41]
49 is the maximum number of photos that can be converted each time.
this GUI programme runs in single thread o cpu not supporting multi thread on gpu 

how can i convert more than 49 images to cartoon in single time

**Comment by TachibanaYoshino** [comment]
Please use the latest AnimeGANv3's UI tool and pre-trained *.onnx to turn your photos into anime.😊
