### ISSUE TITLE
How many data need to train one style?

### ISSUE THREAD

**Issue by superxi** [TachibanaYoshino/AnimeGANv3#43]
Hi, Thanks for your amazing work, I'm wondering how much data you usually need to train a style model?

**Comment by TachibanaYoshino** [comment]
For the landscape style model in the paper, please refer to the paper for its dataset introduction.
For the portrait stylized style, the training code is different from the code used for the open source landscape style, and the amount of data ranges from more than 3,000 to more than 10,000.
