### ISSUE TITLE
自训练模型，最后在Ckpt2pb里无法找到input:AnimeGANv3_input, 后改为 val_input完成pb2onnx, 请问这样对不?

### ISSUE THREAD

**Issue by neoyxm** [TachibanaYoshino/AnimeGANv3#45]
谢谢大大的分享。

我按照readme的指引， 自己训练了模型， 最后用animegan_Ckpt2pb.py将checkpoint转换为onnx 。
脚本里input: AnimeGANv3_input始终无法找到， 后来查看所有op名字找到val_input, 用这个作为input完成了转换。
就是不知道这个input是不是正确的?

**Comment by TachibanaYoshino** [comment]
When training is complete, you need to pick the ckpt weights of the appropriate epoch (Modify the epoch sequence number in the first line of the checkpoint file.), and then use tool/get_generator_ckpt.py to extract the weights containing only the generator. 
like:
`python get_generator_ckpt.py --checkpoint_dir ../checkpoint/AnimeGANv3_Shinkai --save_dir ../checkpoint/generator_v3_Shinkai_weight`

Then use deploy/animegan_Ckpt2pb.py to convert the weight of the generator to pb and onnx. like:
`cd deploy`
Modify the weight path and model file name of animegan_Ckpt2pb.py, and then run
`python animegan_Ckpt2pb.py`
Run test_by_onnx.py to test the onnx model file.

Note that the input node names are defined in tool/get_generator_ckpt.py. At the same time, the input batch size and dimensions are also defined.

**Comment by neoyxm** [comment]
> When training is complete, you need to pick the ckpt weights of the appropriate epoch (Modify the epoch sequence number in the first line of the checkpoint file.), and then use tool/get_generator_ckpt.py to extract the weights containing only the generator. like: `python get_generator_ckpt.py --checkpoint_dir ../checkpoint/AnimeGANv3_Shinkai --save_dir ../checkpoint/generator_v3_Shinkai_weight`
> 
> Then use deploy/animegan_Ckpt2pb.py to convert the weight of the generator to pb and onnx. like: `cd deploy` Modify the weight path and model file name of animegan_Ckpt2pb.py, and then run `python animegan_Ckpt2pb.py` Run test_by_onnx.py to test the onnx model file.
> 
> Note that the input node names are defined in tool/get_generator_ckpt.py. At the same time, the input batch size and dimensions are also defined.

@TachibanaYoshino 

Thanks for your quick reply, and the instructions are so helpful.

**Comment by neoyxm** [comment]
@TachibanaYoshino 

BTW: Would you please put an alipay/wechat pay qrcode in README? I'd like to buy you guys a cup of coffee.

**Comment by TachibanaYoshino** [comment]
> BTW: Would you please put an alipay/wechat pay qrcode in README? I'd like to buy you guys a cup of coffee.

There is currently no relevant qrcode. You can also follow my patreon for more opportunities to communicate.

**Comment by neoyxm** [comment]
> > BTW: Would you please put an alipay/wechat pay qrcode in README? I'd like to buy you guys a cup of coffee.
> 
> There is currently no relevant qrcode. You can also follow my [patreon ](https://www.patreon.com/Asher_Chan) for more opportunities to communicate.

Yeah, I know your Patreon blog to register the member ship. But as you know, nowadays, Chinese don't use the credit cards anymore :(

**Comment by TachibanaYoshino** [comment]
> Yeah, I know your Patreon blog to register the member ship. But as you know, nowadays, Chinese don't use the credit cards anymore :(

It doesn't matter, it's enough to help you.
