### ISSUE TITLE
 Have you tried running your code on an Ubuntu system? There are too many errors, and training is not possible.

### ISSUE THREAD

**Issue by shiyueGG** [TachibanaYoshino/AnimeGANv3#46]

**Comment by TachibanaYoshino** [comment]
Yes, I trained on Ubuntu system. You need to install a suitable operating environment based on your hardware.
For example

## Requirements (2080TI + CUDA10)  
- python 3.7  
- tensorflow-gpu 1.15.0 (GPU 2080Ti, cuda 10.0.130, cudnn 7.6.0)  
- opencv  
- tqdm  
- numpy  
- glob  
- argparse  
- onnxruntime-gpu  


## Requirements (3090 + CUDA11)  
- python 3.8   
- opencv  
- tqdm  
- numpy  
- glob  
- argparse  
- onnxruntime-gpu 
- tensorflow gpu install guidance:  
`pip install --upgrade pip `  
`pip install nvidia-pyindex `  
`pip install nvidia-tensorflow[horovod] `   
`pip install nvidia-tensorboard==1.15 `

**Comment by TachibanaYoshino** [comment]
Yes, I trained on Ubuntu system. You need to install a suitable operating environment based on your hardware.
For example

## Requirements (2080TI + CUDA10)  
- python 3.7  
- tensorflow-gpu 1.15.0 (GPU 2080Ti, cuda 10.0.130, cudnn 7.6.0)  
- opencv  
- tqdm  
- numpy  
- glob  
- argparse  
- onnxruntime-gpu  


## Requirements (3090 + CUDA11)  
- python 3.8   
- opencv  
- tqdm  
- numpy  
- glob  
- argparse  
- onnxruntime-gpu 
- tensorflow gpu install guidance:  
`pip install --upgrade pip `  
`pip install nvidia-pyindex `  
`pip install nvidia-tensorflow[horovod] `   
`pip install nvidia-tensorboard==1.15 `

**Comment by shiyueGG** [comment]
> 是的，我是在Ubuntu系统上训练的。您需要根据您的硬件安装合适的运行环境。 例如
> 
> ## 要求（2080TI + CUDA10）
> * 蟒蛇3.7
> * 张量流GPU 1.15.0（GPU 2080Ti，cuda 10.0.130，cudnn 7.6.0）
> * 开放式计算机视觉
> * 全面质量管理
> * 麻木
> * 全局
> * arg解析
> * Onnx运行时GPU
> 
> ## 要求（3090 + CUDA11）
> * 蟒蛇3.8
> * 开放式计算机视觉
> * 全面质量管理
> * 麻木
> * 全局
> * arg解析
> * Onnx运行时GPU
> * Tensorflow GPU安装指南：
>   `pip install --upgrade pip `
>   `pip install nvidia-pyindex `
>   `pip install nvidia-tensorflow[horovod] `
>   `pip install nvidia-tensorboard==1.15 `

I've been trying since last night and just realized that Python 3.8 was the cause of some issues. After downgrading, I managed to solve a few problems. However, there are still many issues with the training. For instance:

`FileNotFoundError: [Errno 2] No such file or directory: './dataset/Hayao/smooth_noise'`

It might be due to my lack of understanding, but I'm still unable to grasp the required data format for training. I'm still unclear about the entire training dataset format.

Most importantly, I thought this repository didn't have many issues since there was only one visible. But I discovered that over 40 questions from other users were closed. Why were they closed? If they were not closed, it would be easier to find solutions and resolve many issues, right?

**Comment by TachibanaYoshino** [comment]
You can also find answers from other solved or open questions.
The format of the dataset can refer to the directory tree in the dataset. It is worth noting that lines 54 of AnimeGANv3_hayao.py and AnimeGANv3_shinkai.py are different. If you want to get smooth_noise data, you also need to use the tools/get_saltNoise.py script to add noise to the smooth data of this style and convert it to smooth_noise data.

**Comment by shiyueGG** [comment]
> 您还可以从其他已解决或未解决的问题中找到答案。 数据集的格式可以参考数据集中的目录树。值得注意的是，AnimeGANv3_hayao.py 和 AnimeGANv3_shinkai.py 的第 54 行是不同的。如果想要获取smooth_noise数据，还需要使用tools/get_saltNoise.py脚本为该风格的smooth数据添加噪声，转换为smooth_noise数据。

Thank you for your reply. I tried to review the documentation and search the internet, but it didn't solve the problem. I used your method. Solved this problem. But there are other issues: 
Traceback (most recent call last):

  File "/root/miniconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/ops/script_ops.py", line 235, in __call__
    ret = func(*args)

  File "/root/AnimeGANv3/tools/data_loader.py", line 50, in process_image
    image1, image2 = self.read_image(img_path)

  File "/root/AnimeGANv3/tools/data_loader.py", line 45, in read_image
    image2 = cv2.cvtColor(image, cv2.COLOR_BGR2RGB).astype(np.float32)

cv2.error: OpenCV(4.6.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by TachibanaYoshino** [comment]
Please check whether the image path is correct. The image was not read successfully.

**Comment by shiyueGG** [comment]
Finally, it's running and ready for training. But Python edge_ Smooth.py -- dataset Hayao -- img_ Size 256 will compress the image to 256 instead of cropping, so if the material image is not square, it will deform after operation.

**Comment by shiyueGG** [comment]
Get_ Generator_ How to use ckpt to extract weight files after training. I searched for this information for a long time but couldn't find it. Can you explain it in the document? Thank you very much!
