### ISSUE TITLE
win11 not works, not able to install 

### ISSUE THREAD

**Issue by Checkmate** [TachibanaYoshino/AnimeGANv3#49]
tested python 3.10 & python 3.12 , neither works.

**Comment by codehuicn** [comment]
So the python version will be ... And I try it in Windows10, it failed! The error is that "onnxruntime==1.10.0" is unavailable!?

**Comment by TachibanaYoshino** [comment]
#46 
I didn't try it on Windows, but for the installation of dependencies, you need to choose the correct version. You can refer to the relevant dependency versions mentioned in issue 46.
