### ISSUE TITLE
Dependencies Conflict

### ISSUE THREAD

**Issue by MahrukhAliKhanHypersoft** [TachibanaYoshino/AnimeGANv3#52]
Which python version has you used ?? Dependencies conflict is encountered again and again. The conflict between libraries is: onnx==1.10.1
onnxruntime>=1.16.6
tensorflow-gpu==2.10.0

**Comment by TachibanaYoshino** [comment]
git clone https://github.com/TachibanaYoshino/AnimeGANv3.git
cd AnimeGANv3

#If you use cuda10, execute the following command:
```bash
conda create -n AnimeGANv3 python=3.7
conda activate AnimeGANv3
conda install ffmpeg
conda install cudatoolkit=10.0.130 cudnn
pip install opencv-python tqdm  argparse  onnxruntime-gpu  scikit-image joblib numpy==1.19.5 pillow==8.4.0 tf2onnx==1.10.1 coremltools==6.0 tensorflow-gpu==1.15.0
```

 
#If you use cuda11, execute the following command:
```bash
conda create -n AnimeGANv3 python=3.8   
conda activate AnimeGANv3   
conda install ffmpeg     
pip install opencv-python tqdm  argparse  onnxruntime-gpu  scikit-image joblib numpy==1.23.5 pillow==9.0.1 tf2onnx==1.15.1 coremltools==7.0 
pip install --upgrade pip 
pip install nvidia-pyindex 
pip install nvidia-tensorflow[horovod]  
```

#If you use cuda12, execute the following command:
```bash
conda create -n AnimeGANv3 python=3.8   
conda activate AnimeGANv3   
conda install ffmpeg     
pip install opencv-python tqdm  argparse  onnxruntime-gpu==1.19.2 onnx==1.10.1  scikit-image joblib numpy==1.23.5 pillow==9.0.1 tf2onnx==1.10.1 coremltools==7.0 
pip install --upgrade pip 
pip install nvidia-pyindex 
pip install nvidia-tensorflow[horovod]  
```

**Comment by MahrukhAliKhanHypersoft** [comment]
Thank you so much for the help. The issue is resolved now. My cuda version was 12.3 and I used python3.10 version.

**Comment by MahrukhAliKhanHypersoft** [comment]
I have analyze the repository deeply. But I couldn't find pre-trained models of disney, Kpop, USA, comic and oil-painting. Kindly provide link of these pre-trained models. I will be looking forward for your reply

**Comment by nhantamz** [comment]
@TachibanaYoshino Hi bro, how to install your script on Ubuntu 22 server, with RTX 4090 - CUDA 11 - python 3.10? Thanks!
