### ISSUE TITLE
Dose this repo support multi face style tranfer?

### ISSUE THREAD

**Issue by zhaoxuejun1234** [TachibanaYoshino/AnimeGANv3#59]
This repo did an amazing job, but all these examples are based on singe protrait. I wonder if this repo supoort multi-face style transfer. Like the following picture example.
![Uploading Oscar.png…]()

**Comment by zhaoxuejun1234** [comment]
![Oscar](https://github.com/user-attachments/assets/57be7c32-6268-41a1-b5d5-fdd89812930e)

**Comment by TachibanaYoshino** [comment]
It supports image processing containing multiple faces. The first solution is to directly input the image, and the model will convert the entire image content at once, including the portrait and background. However, this method has limited effect on faces with small facial areas. Therefore, you can also use the second method, which can refer to the inference method [repo ](https://github.com/TachibanaYoshino/AnimeGANv3_Portrait_Inference) corresponding to this repo.

**Comment by zhaoxuejun1234** [comment]
> Dear Asher, 
     Thank you very much for your timely response.Its really helps. I have noticed the repo you mentioned and plan to give a try. But I didn’t fina the onnx model mentioned in your run.sh script which named as "AnimeGANv3_large_Kpop.onnx". How can I obtain this onnx model? Looking forward to hearing from you! Thank you for your time again! 
Regards, 
Xuejun Zhao
