### ISSUE TITLE
when will the source code release?

### ISSUE THREAD

**Issue by jinfagang** [TachibanaYoshino/AnimeGANv3#6]
when will the source code release?

**Comment by TachibanaYoshino** [comment]
I'm sorry, this problem can't be determined, and the source code may not be released. We intend to continue to sign a V3-based commercial license with Google, and I want to provide source code and any technical support to Google. Maybe when the authorization date is over or the face animation is released, the source code will be released here.

**Comment by jiangxinufo** [comment]
压缩包密码是什么？

**Comment by ruabliuqiu** [comment]
> when will the source code release?

Your profile picture is so familiar, you ware a great god
