### ISSUE TITLE
About the .zip archive

### ISSUE THREAD

**Issue by zengyanquan** [TachibanaYoshino/AnimeGANv3#9]
I have tried several times for decomplie the models but unfortunately failed. I have realized that the magic head in the file "struct" is different from the modules you mentioned ending with with test_by_onnxZIP in HEX-editor, although I have fixed them, it still comes 
bugs. 
![1](https://user-images.githubusercontent.com/99547700/153717575-b972230d-d499-4a89-89e4-6bb310ec4aff.jpg)
![2](https://user-images.githubusercontent.com/99547700/153717581-63bafd48-cde6-4863-8353-b8852f8e8529.jpg)

 @TachibanaYoshino

**Comment by TachibanaYoshino** [comment]
Decompilation is also difficult and time-consuming. I don't suggest you do so.

**Comment by zengyanquan** [comment]
so how can i get the password of the zip archive？ Thx.



发自我的iPhone


------------------ Original ------------------
From: Asher Chan ***@***.***&gt;
Date: Sun,Feb 13,2022 2:40 AM
To: TachibanaYoshino/AnimeGANv3 ***@***.***&gt;
Cc: zengyanquan ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TachibanaYoshino/AnimeGANv3] About the .zip archive (Issue #9)

**Comment by jeffhecker** [comment]
Reversing engineering doesn't have to be tedious if you can find the right tool. @zengyanquan Since you have already viewed the raw binary, you should be able to easily guess that it is archived with PyInstaller. 

Based on the fact that the exe was just archived with PyInstaller, there's a lot of tools to unpack it. A good example would be [pyinstxtractor](https://github.com/extremecoders-re/pyinstxtractor). Then you can recover the original source code from Python byte codes(`.pyc`) simply using decompilers such as [uncompyle6](https://pypi.org/project/uncompyle6/).

**Comment by zengyanquan** [comment]
i indeed have already used pyinstxtrator to unpack the exe，and tried to use uncompyle6 to decompile the pyc but failed. you can see the results in my attachments in the issue. Thanks for your replying and help.



发自我的iPhone


------------------ Original ------------------
From: jeffhecker ***@***.***&gt;
Date: Sun,Feb 13,2022 2:52 PM
To: TachibanaYoshino/AnimeGANv3 ***@***.***&gt;
Cc: zengyanquan ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [TachibanaYoshino/AnimeGANv3] About the .zip archive (Issue #9)





 
Reversing engineering doesn't have to be tedious if you can find the right tool. @zengyanquan Since you have already viewed the raw binary, you should be able to easily guess that it is archived with PyInstaller.
 
Based on the fact that the exe was just archived with PyInstaller, there's a lot of tools to unpack it. A good example would be pyinstxtractor. Then you can recover the original source code from Python byte codes(.pyc) simply using decompilers such as uncompyle6.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liuxz656** [comment]
> 

I encountered the same problem, have you solved it?

**Comment by zengyanquan** [comment]
Sorry, I didn’t figure it out, maybe you can ask the developer.






------------------ Original ------------------
From: liuxz656 ***@***.***&gt;
Date: Sun,Apr 9,2023 2:58 AM
To: TachibanaYoshino/AnimeGANv3 ***@***.***&gt;
Cc: zengyanquan ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [TachibanaYoshino/AnimeGANv3] About the .zip archive (Issue #9)





   
I encountered the same problem, have you solved it?
